# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "psPYd55mf4ExB5ak24lHrBPMRynhayxEME4UhPX+AVGcON3H29k/G8ZXP2LHA4O9XHpE/VmYJX/P4BZ7UzMTEOEF+4aQbK892meIAIzLZtkAG1rARb6BJ0MMxND0UqEhpmOOkKddmOcXNaIscEuw1iO9+Q0wQmGDIJ90zDVWNBgJ2YXv1dDA22sw++SLK6G8hGRc8oX6p85gQ2rDa8W1WROeytF7Y+BHatk5mFEh7IQc6ofJgETsiOU3a51zzIR16AMOhXJKPK2vs44rfML1+soW6dYkQFbHri54GZuQkn6spsybuK0RdrUGlHhbtHK5YOjWqlDHdrKpo+8fVDhd2hhJ9lZAkGBDYg0gNslgfdWf/UMJXAgpk3MEJQmK1chTPlMAAW3x0wq45oRqBwGRtehYV+idJTLD10VqB2e4oi56Q/u3Y1i7iEREMG/XnuMF6jmWUj0afpq7RwTDfIgSjlLVurrHmDP8Py7bwiZTxbbISlI016cVMnbGXc7SpCR0xc6WWGSAmM8YfIg6Ot2pfZk+Z4VxZBNnVwZrmals6hurmE/ug+OCoFxY2o/HaVHk7PQP9wT8CjaPuqBAyrNHqdO9hzw7STLxfqHM10A2WtvzHz6rkGOqlshq3likgqVQ7zeH8ZQ0jQuqOnB5zF84gzJR+kyM8cVk5y4M9ud76o0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
